### ISSUE TITLE
Whitepaper page navigation isn't obvious

### ISSUE THREAD

**Issue by jorisbontje** [MakerDAO/docs#1]
The whitepaper should be a long scrolling document, or have a very clear internal navigation at least. The current pulldown navigation at the top of the page isn't very obvious.

**Comment by cassiopaia** [comment]
will look into .. and talked with rune about adding a pagination at bottom

**Comment by cassiopaia** [comment]
quick and dirty for now .. .have to look into again when get more time to .. let me know if this would work for now .. https://github.com/MakerDAO/docs/commit/7ee8699712406e94cf1732c95cb5c3e4fc1eeeef

**Comment by jorisbontje** [comment]
Works for me!
