### ISSUE TITLE
Chat link should link to Slack signup page

### ISSUE THREAD

**Issue by jorisbontje** [MakerDAO/docs#16]
Should link to https://makerdao.herokuapp.com/

Now it links to https://makerdao.slack.com which you can only access if you have an account already.

**Comment by cassiopaia** [comment]
why not go with https://slack.makerdao.com?

**Comment by jorisbontje** [comment]
Even better

**Comment by cassiopaia** [comment]
we should start linking to chat.makerdao.com -- thoughts?

**Comment by nmushegian** [comment]
yes
